# Generated by Django 2.1.2 on 2019-09-04 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('inventory_created_time', models.DateField()),
                ('inventory_updated_time', models.DateField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='StoreStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_quantity', models.IntegerField()),
                ('inventory_created_time', models.DateField()),
                ('inventory_updated_time', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
            options={
                'db_table': 'store_stock',
            },
        ),
        migrations.AlterUniqueTogether(
            name='storestock',
            unique_together={('store', 'product')},
        ),
    ]
